### PR TITLE
Master upstream dev 17.05

### PR DESCRIPTION
**Pull request by mbolivar**

### CODE REVIEW

**Comment by mike-scott** [comment]
Tested this branch on K64F for basic functionality (no OTA)
Tested-by: Michael Scott <michael.scott@linaro.org>

**Comment by mbolivar** [comment]
I've OTAed Carbon and Nitrogen using this branch, https://github.com/Linaro/mcuboot/pull/7, and https://github.com/mbolivar/zephyr-fota-hawkbit/commit/3d093185413c18a974dca0dcd5f9a19ccbc76d66.

(That FOTA commit was based off of an earlier version of an update from @mike-scott  -- that has changed a bit in the latest FOTA review from him today, but not substantially. diff: https://hastebin.com/tusiyiheja.cpp)

Will retest with Michael's latest on Monday.

**Comment by mike-scott** [comment]
I'm a bit nervous at how quickly these merges will quickly get stale if we can't get them verified and approved in a fairly streamlined manner.

**Comment by mbolivar** [comment]
I agree. I think this one is a little delayed because of all the (good and needed) changes on the FOTA side you've put together in https://github.com/Linaro/zephyr-fota-hawkbit/pull/83. We can merge them together, and then do another merge from Zephyr master, right?

**Review by rsalveti — APPROVED** [review]

**Comment by rsalveti** [comment]
+1 to merge everything and propose another master merge.

**Review by mike-scott — APPROVED** [review]
LGTM

**Pull request merged**
