### PR TITLE
MQTT patches

### PR DESCRIPTION
**Pull request by mike-scott**

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Review by rsalveti — APPROVED** [review]
LGTM, did you also forward these patches upstream?

**Comment by gatek33p3r** [comment]
Sanity Check Succeeded.

**Comment by mike-scott** [comment]
Not yet, I have a larger patchset going which removes the silly PUBLISHER / SUBSCRIBER app type.  I could probably start with these.

**Comment by mike-scott** [comment]
And ugh, the 3rd patch description is wrong still.

Let me fix that.

**Comment by rsalveti** [comment]
Cool, fine to have them in.

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Sanity Check Succeeded.

**Pull request merged**
