### PR TITLE
Revert "defconfig: 96b_nitrogen: Enable the SPI slave driver by default"

### PR DESCRIPTION
**Pull request by rsalveti**
This reverts commit 99ae158d92f5ec6b08dae69166a09509be790df7.

### CODE REVIEW

**Comment by rsalveti** [comment]
No need to have this patch anymore since we can now debug and use SPI on carbon.

**Review by EmbeddedAndroid — APPROVED** [review]
LGTM. I build tested it on top of master-upstream-dev and now all targets we care about pass the sanity check.

https://ci.arm64.io/job/zephyr-dev/12/

**Comment by EmbeddedAndroid** [comment]
This patch fixes that last issue remaining issue from Linaro/zephyr-fota-hawkbit#19

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by gatek33p3r** [comment]
Sanity Check Succeeded.

**Review by mike-scott — APPROVED** [review]

**Comment by mike-scott** [comment]
Included in the latest rebase.

**Pull request closed without merging**
