### PR TITLE
Bluetooth: HCI SPI: set RX BUF LEN to SPI MAX LEN

### PR DESCRIPTION
**Pull request by rsalveti**
CMD pool size depends on RX BUF LEN, so set that to the max length the
driver is able to receive over SPI.

Change-Id: Ib35e2220c20d12b30ac75ad8bd59d6e57a09b981
Signed-off-by: Ricardo Salveti <ricardo.salveti@linaro.org>

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Sanity Check Failed.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Sanity Check Succeeded.

**Comment by mike-scott** [comment]
LGTM

**Pull request merged**
