### PR TITLE
net/mqtt: cleanup TX function unref handling

### PR DESCRIPTION
**Pull request by mike-scott**
With CONFIG_NET_DEBUG_NET_BUF enabled, the log messages are full of errors
regarding NULL parameters passed into net_buf_unref in almost every
TX function for handling MQTT messages:
mqtt_tx_connect()
mqtt_tx_disconnect()
mqtt_tx_pub_msgs()
mqtt_tx_publish()
mqtt_tx_pingreq()
mqtt_tx_subscribe()
mqtt_tx_unsubscribe()
mqtt_parser()

Let's clean up the unref handling so that our debug log isn't quite
so full of error spam (as opposed to the normal amount of spam from
the net buf log).

Change-Id: Ib49d1192f51abe4329e6dc9da3c51a4a36290082
Signed-off-by: Michael Scott <michael.scott@linaro.org>

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by rsalveti** [comment]
LGTM, but not yet tested. Probably easy to upstream this one.

**Comment by gatek33p3r** [comment]
Sanity Check Succeeded.

**Comment by mike-scott** [comment]
Woops rebasing.

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Sanity Check Succeeded.

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Sanity Check Succeeded.

**Pull request closed without merging**
